@Library('jenkins-shared-lib@main') _
import build.buildApplication

pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                buildApplication(appName: 'app1')
            }
        }
    }
}
